[package]
name = "base64-cfl-wrapper"
version = "0.1.0"
authors = ["Nick Stevens <nick@bitcurry.com>"]

[dependencies]
fixedvec = "0.1.0"

[dependencies.base64]
git = "https://github.com/nastevens/base64-noalloc.git"

[lib]
crate-type = ["staticlib"]
